package com.mustafayigit.dynamiccolor.ui.theme

import androidx.compose.ui.graphics.Color

val light_primary = Color(0xFF286b2a)
val light_onPrimary = Color(0xFFffffff)
val light_primaryContainer = Color(0xFFabf5a3)
val light_onPrimaryContainer = Color(0xFF012104)
val light_secondary = Color(0xFF52634e)
val light_onSecondary = Color(0xFFffffff)
val light_secondaryContainer = Color(0xFFd5e8ce)
val light_onSecondaryContainer = Color(0xFF101f0f)
val light_tertiary = Color(0xFF38656a)
val light_onTertiary = Color(0xFFffffff)
val light_tertiaryContainer = Color(0xFFbcebf0)
val light_onTertiaryContainer = Color(0xFF011f22)
val light_error = Color(0xFFba1b1b)
val light_errorContainer = Color(0xFFffdad4)
val light_onError = Color(0xFFffffff)
val light_onErrorContainer = Color(0xFF410001)
val light_background = Color(0xFFfcfdf6)
val light_onBackground = Color(0xFF1a1c19)
val light_surface = Color(0xFFfcfdf6)
val light_onSurface = Color(0xFF1a1c19)
val light_surfaceVariant = Color(0xFFdee5d8)
val light_onSurfaceVariant = Color(0xFF424840)
val light_outline = Color(0xFF73796f)
val light_inverseOnSurface = Color(0xFFf1f1eb)
val light_inverseSurface = Color(0xFF2f312d)
val light_inversePrimary = Color(0xFF90d789)
val light_shadow = Color(0xFF000000)

val dark_primary = Color(0xFF90d789)
val dark_onPrimary = Color(0xFF003907)
val dark_primaryContainer = Color(0xFF085315)
val dark_onPrimaryContainer = Color(0xFFabf5a3)
val dark_secondary = Color(0xFFbaccb3)
val dark_onSecondary = Color(0xFF253423)
val dark_secondaryContainer = Color(0xFF3c4b39)
val dark_onSecondaryContainer = Color(0xFFd5e8ce)
val dark_tertiary = Color(0xFFa1cfd4)
val dark_onTertiary = Color(0xFF00363b)
val dark_tertiaryContainer = Color(0xFF1e4d52)
val dark_onTertiaryContainer = Color(0xFFbcebf0)
val dark_error = Color(0xFFffb4a9)
val dark_errorContainer = Color(0xFF930006)
val dark_onError = Color(0xFF680003)
val dark_onErrorContainer = Color(0xFFffdad4)
val dark_background = Color(0xFF1a1c19)
val dark_onBackground = Color(0xFFe2e3dd)
val dark_surface = Color(0xFF1a1c19)
val dark_onSurface = Color(0xFFe2e3dd)
val dark_surfaceVariant = Color(0xFF424840)
val dark_onSurfaceVariant = Color(0xFFc2c8bd)
val dark_outline = Color(0xFF8c9288)
val dark_inverseOnSurface = Color(0xFF1a1c19)
val dark_inverseSurface = Color(0xFFe2e3dd)
val dark_inversePrimary = Color(0xFF286b2a)
val dark_shadow = Color(0xFF000000)



val seed = Color(0xFF1b5e20)
val error = Color(0xFFba1b1b)